### ISSUE TITLE
Trouble compiling bootstrap-sass

### ISSUE THREAD

**Issue by arminbauer** [untyped/sbt-plugins#61]
I have a strange error when I compile bootstrap-sass from https://github.com/twbs/bootstrap-sass. The error is:

java.io.FileNotFoundException: /project/app/assets/bootstrap/mixins (Is a directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:131)
	at sbt.Using$$anonfun$fileReader$1.apply(Using.scala:86)
	at sbt.Using$$anonfun$fileReader$1.apply(Using.scala:86)
	at sbt.Using$$anon$2.openImpl(Using.scala:72)
	at sbt.OpenFile$class.open(Using.scala:46)
	at sbt.Using$$anon$2.open(Using.scala:70)
	at sbt.Using$$anon$2.open(Using.scala:70)
	at sbt.Using.apply(Using.scala:24)
	at sbt.IO$.readLines(IO.scala:677)
	at com.untyped.sbtsass.CssSource.parents$lzycompute(CssSource.scala:18)
	at com.untyped.sbtsass.CssSource.parents(CssSource.scala:16)
	at com.untyped.sbtgraph.Graph$class.parents(Graph.scala:172)
	at com.untyped.sbtsass.Graph.parents(Graph.scala:6)
	at com.untyped.sbtgraph.Graph$class.com$untyped$sbtgraph$Graph$$$plus$eq(Graph.scala:30)
	at com.untyped.sbtgraph.Graph$$anonfun$com$untyped$sbtgraph$Graph$$$plus$eq$1.apply(Graph.scala:30)
	at com.untyped.sbtgraph.Graph$$anonfun$com$untyped$sbtgraph$Graph$$$plus$eq$1.apply(Graph.scala:30)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at com.untyped.sbtgraph.Graph$class.com$untyped$sbtgraph$Graph$$$plus$eq(Graph.scala:30)
	at com.untyped.sbtgraph.Graph$class.$plus$eq(Graph.scala:22)
	at com.untyped.sbtsass.Graph.$plus$eq(Graph.scala:6)
	at com.untyped.sbtsass.Plugin$$anonfun$sourceGraphTask$1$$anonfun$apply$6$$anonfun$apply$8.apply(Plugin.scala:86)
	at com.untyped.sbtsass.Plugin$$anonfun$sourceGraphTask$1$$anonfun$apply$6$$anonfun$apply$8.apply(Plugin.scala:86)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at com.untyped.sbtsass.Plugin$$anonfun$sourceGraphTask$1$$anonfun$apply$6.apply(Plugin.scala:86)
	at com.untyped.sbtsass.Plugin$$anonfun$sourceGraphTask$1$$anonfun$apply$6.apply(Plugin.scala:70)
	at com.untyped.sbtsass.Plugin$.time(Plugin.scala:35)
	at com.untyped.sbtsass.Plugin$$anonfun$sourceGraphTask$1.apply(Plugin.scala:70)
	at com.untyped.sbtsass.Plugin$$anonfun$sourceGraphTask$1.apply(Plugin.scala:69)
	at scala.Function11$$anonfun$tupled$1.apply(Function11.scala:35)
	at scala.Function11$$anonfun$tupled$1.apply(Function11.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)

Unfortunately, I was unable to pin down the problem yet.

**Comment by davegurnell** [comment]
Closing this issue as it's extremely old.
